/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Kitsuneko (https://sketchfab.com/kitsuneko_3d)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/duck-b78442de2bc542ef9393608c40664aa1
Title: Duck
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import scene from '../assets/3d/duck.glb'

const Duck = ({ currentAnimation, ...props }) => {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(scene)
  const { actions } = useAnimations(animations, group)

    useEffect(() => {
        Object.values(actions).forEach((action) => action.stop());
        
        if(actions[currentAnimation]) {
            actions[currentAnimation].play();
        }
    }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.506}>
          <group name="c03cce1450874a9b8d3100814bff55e2fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Armature" scale={0.1}>
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh
                      name="Object_26"
                      geometry={nodes.Object_26.geometry}
                      material={materials.Material_101}
                      skeleton={nodes.Object_26.skeleton}
                    />
                    <skinnedMesh
                      name="Object_27"
                      geometry={nodes.Object_27.geometry}
                      material={materials.Material_75}
                      skeleton={nodes.Object_27.skeleton}
                    />
                    <skinnedMesh
                      name="Object_28"
                      geometry={nodes.Object_28.geometry}
                      material={materials.Material_50}
                      skeleton={nodes.Object_28.skeleton}
                    />
                    <skinnedMesh
                      name="Object_29"
                      geometry={nodes.Object_29.geometry}
                      material={materials.Material_25}
                      skeleton={nodes.Object_29.skeleton}
                    />
                    <skinnedMesh
                      name="Object_30"
                      geometry={nodes.Object_30.geometry}
                      material={materials.Material_37}
                      skeleton={nodes.Object_30.skeleton}
                    />
                    <skinnedMesh
                      name="Object_31"
                      geometry={nodes.Object_31.geometry}
                      material={materials.Standardmaterial}
                      skeleton={nodes.Object_31.skeleton}
                    />
                    <skinnedMesh
                      name="Object_32"
                      geometry={nodes.Object_32.geometry}
                      material={materials.Material_115}
                      skeleton={nodes.Object_32.skeleton}
                    />
                    <skinnedMesh
                      name="Object_33"
                      geometry={nodes.Object_33.geometry}
                      material={materials.Material_88}
                      skeleton={nodes.Object_33.skeleton}
                    />
                    <group
                      name="Object_25"
                      position={[-0.494, 0.222, -0.253]}
                      rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                      scale={0.1}
                    />
                  </group>
                </group>
                <group
                  name="Duck"
                  position={[-0.494, 0.222, -0.253]}
                  rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                  scale={0.1}
                />
                <group
                  name="Lamp"
                  position={[407.625, 590.386, -100.545]}
                  rotation={[1.89, 0.881, -2.045]}
                  scale={100}>
                  <group name="Object_36" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_37" />
                  </group>
                </group>
                <group
                  name="Camera"
                  position={[748.113, 534.367, 650.764]}
                  rotation={[Math.PI, 0.756, 2.68]}
                  scale={100}>
                  <group name="Object_39" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Duck;
